language: objective-c
before_install:
  - brew update
  - brew unlink xctool
  - brew install xctool
script:
  - xctool -workspace Tests/NSString-HYPFormula.xcworkspace -scheme NSString-HYPFormulaTests -sdk iphonesimulator build test
